### ISSUE TITLE
Issues with popping items from arrays?

### ISSUE THREAD

**Issue by samuelgoodell** [anywhichway/proxy-observe#10]
When I use the library and try to pop an element from an array, I get a somewhat useless change event.  This is in node.js v6.2.0.

The code:

``` javascript
require("proxy-observe");

let array = [1, 2, 3];
let proxy = Array.observe(array, function(changes) {
    console.log(changes);
}, ["add", "update", "delete", "splice"]);

proxy.pop();
```

The result:

```
[ { object: [ 1, 2, 3 ],
    type: 'splice',
    index: 3,
    removed: [],
    addedCount: 0 } ]
```

Furthermore, the proxy array is not modified in any way.  Am I doing something wrong?  Other methods such as `push`, `splice`, and `shift` work as expected.

**Comment by anywhichway** [comment]
Fixed, unit tests updated, pushed to npmjs.org
