### ISSUE TITLE
Will this still work in Node when moved from V8?

### ISSUE THREAD

**Issue by slowmove** [anywhichway/proxy-observe#12]
Since, as you mentioning, Google is removing Object.observe from Chrome and V8. Do this plugin use the standard implementation or will it still work in Node using some kind of fallback/polyfill solution?

**Comment by anywhichway** [comment]
This is a replacement for Object.observe; so the answer is it will work. However, it will not work in older versions of Chrome because Proxy is not supported in them and this code requires Proxy to work.

**Comment by Globik** [comment]
Not good usable in node.js module system. 
require('proxy-observe'), but then error: object.observe is not a function. Any idea how to wrap those special to node.js module?

**Comment by slowmove** [comment]
@Globik still works for me though? Don't really understand what you mean?

**Comment by anywhichway** [comment]
@Globik, please post the specific error message you are getting with the file/line number.

**Comment by Globik** [comment]
I mean, how to use this module from within node.js scripting. I see, that Observe is a global function in a browser instance, but what about node.js? How to call correctly?
 Trying like this
var observ=require('proxy-observe')
And what now?
var object = { foo: null };
object = observ.observe(object, function(changeset) {
    console.log(changeset)
});
object.foo = "bar";
Says that observe() is not a function.
Besides in index.js I can't see any lexic for module.exports.
How to be correctly?

**Comment by Globik** [comment]
@slowmove  where do you work with proxy-observe? From within node.js instance or on a frontend from within a browser?

**Comment by anywhichway** [comment]
Because Object.observe is a method added to the global Object, you do not need to and should not assign anything to the result of require("proxy-observe"). 

The code below should print out changes to the object:

```
require("proxy-observe");
var to = {property:true};
function onUpdate(changes) {
    console.log(changes);
}
to = Object.observe(to,onUpdate,["update"]);
to.property = false;
```

The reason you do not see any module exports in the source is because they are not needed. See this line:

```
Object.observe = function(object,callback,acceptlist,pausable,pause,delay) {
     return new Observer(object,callback,acceptlist,pausable,pause,delay);
};
```

**Comment by Globik** [comment]
@anywhichway  thank you very much for your explanation, now I can see it is working. As a global.

**Comment by anywhichway** [comment]
@Globik you are welcome!
