### ISSUE TITLE
Chrome 52 introduce wrong proxy behavior

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#14]
updating to chrome 52 Object.keys give you also non enumerable properties.
On edge and firefox and chrome 51it's allright.

This behavior broken my custom deepObserve (obj+array obs mix). I'm looking for a workaround, 
but I suspect it brokes also your deepObserve due to use of Object.keys. That call should filter **observerCallbacks** and **observers** to skip it otherwise it would go in infinite loop.
To be cleaner target.propertyIsEnumerable(x) could be used also. It works.

This is a sample code that reproduce chrome wrong behavior. Just run it in your browser.
It should not print any variables.

``` javascript
<script>
var target={};
Object.defineProperty(target,"__observerCallbacks__",{enumerable:false,configurable:true,writable:false,value:['aaaa']});
var ori='';
Object.keys(target).forEach(
  function(x){
     ori+=x;
  }
);
var proxy='';
var p = new Proxy(target, {get:function(target,property)
    {
        return property;
    }
});
Object.keys(p).forEach(
  function(x){
    //if (window.target.propertyIsEnumerable(x)){
        proxy+=x;
    //}
  }
);
alert('ori '+ori+' proxy '+proxy);

</script>
```

http://stackoverflow.com/questions/38615647/chrome-52-object-keys-bug-inside-object-js-proxy/38616227#38616227

**Comment by anywhichway** [comment]
If I have read your comment correctly, Chrome 52 breaks with the ECMA spec. If this is the case, then we will not attempt to fix unless Chrome 53 also breaks or Google makes an official statement they won't fix this problem. This must be creating a lot of problems for a lot of people beyond those that use proxy-observe. Leaving the issue open for now, but flagging as won't fix.

**Comment by dmiorandi** [comment]
Ok @anywhichway I'm with you. The intent of this issue is just to warning other users about it.
Google are working to solve the bug. Here there is my ticket
https://bugs.chromium.org/p/chromium/issues/detail?id=632305#c8

**Comment by dmiorandi** [comment]
Chrome 53 back to work.
