### ISSUE TITLE
Delay is not defined by "add" 

### ISSUE THREAD

**Issue by Globik** [anywhichway/proxy-observe#15]
Hi, I am on node.js v6.1.0. Stopped at a very basic example:
require('proxy-observe');
var to={property:true};
function onupdate(change){
	console.log('changes: ',change);
}
to=Object.observe(to, onupdate, ["add","update","reconfigure"]);
to.property=false;
to.another="Hello world!";
With an error like this:
changes:  [ { object: { property: false },
    name: 'property',
    type: 'update',
    oldValue: true } ]
C:\Users\User\node_modules\proxy-observe\index.js:80
                                deliver(false,(typeof(deliver.delay)==="number
? delay : 10));

  ^

ReferenceError: delay is not defined
    at Observer.set (C:\Users\User\node_modules\proxy-observe\index.js:80:62)
    at Object.<anonymous> (C:\Users\User\c.js:14:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
So there is a question if proxy-observe does not allow extensions?

**Comment by anywhichway** [comment]
@Globik, we just pushed a new version v0.0.19 that should fix this. Let us know. The delay capability was pushed at the request of another user and it looks like we did not test it well enough. v0.0.19 HAS NOT been published to NPM, so you need to get it from GitHub. We will push to NPM after you confirm the fix.

**Comment by Globik** [comment]
I have cloned this version 0.0.19. Sorry to say, the same error with an undefined delay from within node.js.
Interesting that all tests via npm test command are running without errors. 
As for a google chrome canary v56.0 those code snippet works OK.

**Comment by anywhichway** [comment]
Odd, just walked through the code and can't find a standalone reference to "delay". Can you verify the line number is the same as last time?

`deliver(false,(typeof(deliver.delay)==="number" ? delay : 10));`

has been replaced with

`deliver(false,(typeof(deliver.delay)==="number" ? deliver.delay : 10));`

**Comment by Globik** [comment]
In the morning I look at it more detailed.

**Comment by Globik** [comment]
Just wondering , in the index.js line 20,  'deliver.delay = delay;', where is deliver from? Perhap this=me.deliver?

**Comment by Globik** [comment]
OK, guys, all is fine. This version is working now good with no error. I have forgotten in my testing script to require a newer version of proxy-observe.
Nice job, a big thank you.
One can place now to npm.

**Comment by anywhichway** [comment]
deliver is the function defined on line 19. delay is an argument to the constructor on line 17.

**Comment by anywhichway** [comment]
pushed to npm
