### ISSUE TITLE
Problem with splice and update

### ISSUE THREAD

**Issue by saper639** [anywhichway/proxy-observe#22]
I made my function to analyze the array of objects. DeepObserve gives too much information when using Splice. So I tried to combine the Array.observe and Object.deepObserve. This allowed me to track the status of the array when you add or change it. And really just get treatment when you change properties in objects. 
In the end, I get a few able to add, delete, - if you change the array (push, splice, pop, etc.), update - when you change the properties of the object in the array.

function myObserve(target, callback) {
  function analizObj(change) {
        if (change.keypath.indexOf('.') > 0) {
              change.type = 'update';
	      var arr = change.keypath.split('.');
              if (!isNaN(arr[0])) change.object = target[arr[0]];                         
         } else if (!isNaN(change.name) && _.isEqual(change.newValue, change.oldValue)) {             
	     return false;	
           } else if (!isNaN(change.name)) {
                change.type = 'reconfigure';
                change.object = target[change.name];                          
             }
        return change; 
  }
  function analizArray(change) {
     if (change.type == 'splice' && change.addedCount == 0) 
        change.type = 'remove';
     if (change.type == 'splice' && change.addedCount > 0) {
        change.newValue = change.object[change.index];       
        change.type = 'add';
     }        
     delete change.object;  
     return change;
  }
  target = Array.observe(target, function(change) { 
    // when you add a new objectof override the new observer
     target = Object.deepObserve(target, function(change) {             
           change = analizObj(change);
           if (change) return callback(change);
     })      
     return callback(analizArray(change));
  }, ["add", "delete", "splice"]);  
  target = Object.deepObserve(target, function(change) {             
	   change = analizObj(change);
           if (change) return callback(change);
  })  
  return target; 
}

The problem I faced. Help to solve it. Example:
var object = [{id:1, d:'cool', usr:[]}, {id:2, d:'cool2'}];
object = myObserve(object, (change)=>{
 console.log(change);
});
object.splice(0, 1);
var tr = _.find(object, {'id':2});
_.set(tr, 'test.new', [3,2,1]);

Return:

{ type: 'remove',
  index: 0,
  removed: [ { id: 1, d: 'cool', usr: [] } ],
  addedCount: 0 }

{ name: 'test',
  object: undefined,
  type: 'update',
  oldValue: undefined,
  newValue: {},
  keypath: '1.test' }

{ name: 'new',
  object: undefined,
  type: 'update',
  oldValue: undefined,
  newValue: [ 4, 5, 6 ],
  keypath: '1.test.new' }

Returns an incorrect index. Had to return keypath: `0.test.new`. Because the element with the 0 index was previously deleted. How to fix the error? Why the index is not rebuilt?

**Comment by anywhichway** [comment]
I am sorry, I have read your comment multiple times and just don't quite get what you are saying other than there is some bug with splice. Can you try to explain differently?

**Comment by saper639** [comment]
Easy example with my problem:
var obj = [{ name: 'Green' }];
obj = Object.deepObserve(obj, (change)=> {
    console.log(change);
});
obj.push({name: 'White'});
obj.push({name: 'Black'});
obj.splice(1,1);

output:
{ name: '1',
  object: [ { name: 'Green' }, { name: 'White' } ],
  type: 'add',
  oldValue: undefined,
  newValue: { name: 'White' },
  keypath: '1' }
{ name: '2',
  object: [ { name: 'Green' }, { name: 'White' }, { name: 'Black' } ],
  type: 'add',
  oldValue: undefined,
  newValue: { name: 'Black' },
  keypath: '2' }
{ name: '2',
  object: [ { name: 'Green' }, { name: 'Black' },  ],
  type: 'delete',
  oldValue: { name: 'Black' },
  newValue: undefined,
  **keypath: '2'** } - Why are there 2? Since the removed element at index 1.

**Comment by saper639** [comment]
I understand what it is. I a little incorrectly modified Your library. Sorry.

**Comment by anywhichway** [comment]
@saper639 Thanks for resolving yourself!
