### ISSUE TITLE
Uncaught TypeError: Object.observe is not a function

### ISSUE THREAD

**Issue by bhavyeg** [anywhichway/proxy-observe#23]
I tried to run the example given in the readme and got this error. I am using Chrome - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by anywhichway** [comment]
@bhavyeg Looking into this

**Comment by anywhichway** [comment]
@bhavyeg We have checked in a file test/issue23.html with the code from the README. Please try and load this in your browser with the debugger open. It appears to work.

**Comment by anywhichway** [comment]
no response to advice
