### ISSUE TITLE
Wrong array index managment

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#3]
this.length not this.length-1. I.e. on push element is added ad n-1 position instead n.
push and pop methods

``` javascript
         return this.splice(this.length-1,0,item);
```

``` javascript
         return this.splice(this.length-1,1);
```

**Comment by anywhichway** [comment]
Looking into this. Will have a response by 5/9/2016.

**Comment by anywhichway** [comment]
There is a release candidate with this fix checked in as branch 0.0.11.

**Comment by dmiorandi** [comment]
tks @anywhichway. I'll try on tomorrow

**Comment by anywhichway** [comment]
release candidate in v0.0.12 branch
