### ISSUE TITLE
Start observing later

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#4]
is is possible to start to observe later. I mean define observer in init phase, but do not fire callbacks
immediatly. Start to fire (ignorign previus notifies) only when I decide to do it.

This is cause I'm creating a recursive observer (object+array) of a json and creation is a little heavy cause a lot of non desired events are created on init phase.

I don't know if you deep observer is usable in my case or if is lighter.

**Comment by anywhichway** [comment]
We will look into this, although it is not part of the "standard" observe spec ... of course now that observe has been deprecated, I am not sure there is a standard ;-)

**Comment by anywhichway** [comment]
There is a release candidate with this fix checked in as branch 0.0.11. See code and README for documentation on use.

**Comment by dmiorandi** [comment]
tks @anywhichway, seems to be in the right direction. I'll try on tomorrow.

**Comment by dmiorandi** [comment]
So that if I understand code should be something like:

``` javascript
var myobj={......};
var proxy=object.observe(myobj,mycallback,["add", "update", "delete"],true,true);

/// Later to start observing:
proxy.deliver(true);
```

But this code doesn't work cause deliver() function is not found on proxy. Looking at source code
it seems that deliver function is not exposed on proxy, but is local to Observer. Am I wrong? 
Any suggestions?

Actually to make it work I've made a patch on 

``` javascript
function Observer{
....
this.deliver=deliver;
....
```

so that on my application I've made something like this to enable observing after creation of observers:

``` javascript
    Enumerable
        .from(observerData.subObserversReferences)
        .forEach(proxy=>{
          Enumerable
            .from(proxy.__observers__)
            .forEach(observer=>{
                observer.deliver.pause=false;
                observer.deliver(true);
            })
        });
```

This is ugly but it works. I think this is not what you mean on your changes, I suppose.

**Comment by anywhichway** [comment]
Actually, deliver should be available, although also an ugly approach, via the get trap for the proxy starting line 35. Note the Observer is actually a trap handler. We will try your approach which is a little cleaner and try to write some more unit tests (not easy in the world of observables):

```
            me.get = function(target, property) {
                if(property==="__observer__") {
                    return me;
                }
                if(pausable && property==="deliver") {
                    return deliver;
                }
                return target[property];
            }
```

**Comment by anywhichway** [comment]
release candidate in v0.0.12 branch
