### ISSUE TITLE
array splice wrong behaviors

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#5]
Inside splice function there are two errors:
- removed, slice function have wrong end index
- addedCount is 1 more than right value.

``` javascript
proxy.splice = function(start,end) {
  var removed = this.slice(start,end);         // wrong always emtpy cause end have to start from start
  var addedCount = arguments.length-1; //wrong, typically length is 3 when addedCount is 1
```

so that working code I've tested is

``` javascript
proxy.splice = function(start,end) {
  var removed = this.slice(start,start+end);
  var addedCount = arguments.length>1?arguments.length-2:0;
   .......
  };
```

Could you fix this?

Tks

**Comment by anywhichway** [comment]
Researching. Should be able to resolve within a couple of days.

**Comment by anywhichway** [comment]
Bug confirmed, adding your recommended code, will push a fix when we have some better unit tests in place over the next few days. The lack of unit tests on this package is hurting. We had not paid much attention to it until Chrome dropped observe a few weeks ago.

**Comment by dmiorandi** [comment]
I think this library is very usefull, so that is a pleasure help you to
make it fixed.
For sure a set of unit test is mandatory to garantize it work properly.

2016-05-09 13:50 GMT+02:00 Simon Y. Blackwell notifications@github.com:

> Bug confirmed, adding your recommended code, will push a fix when we have
> some better unit tests in place over the next few days. The lack of unit
> tests on this package is hurting. We had not paid much attention to it
> until Chrome dropped observe a few weeks ago.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/anywhichway/proxy-observe/issues/5#issuecomment-217843784

## 

Dott. Denis Miorandi
via dei Vignai 27
38060 - Nogaredo (TN)

**Comment by anywhichway** [comment]
release candidate in v0.0.12 branch
