### ISSUE TITLE
Object observer always notify a child of type array

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#7]
I'm using a combination of object and array observer to observer a json complex tree.
I've got undesired notification when an array is nested inside  an object and arrat element change.
I don't know if this is right or not when observing object but in my case is unsedired and kill down performance. This is the behavior:

var x={
     a:array[items:Object]
}

when an array item change I've got a notification on x that says that 'a' fileld was changed.
This is normal when you intend just to monitor x, but in my case I expect that item observer work, not
the father one.
I don't know how to achieve this. Probably an 'ignore array fields changes' on object observer  could do the trick. I've got no better ideas.

All in all I need make a deep observing doing differenct actions on array and objects. Do you think
your deepobserver could do this?

**Comment by anywhichway** [comment]
So are you saying that you are observing both x and x.a in your example? 

Are you also saying, 

1) that when you are modifying x.a by inserting or deleting an element you are getting notification to x in addition to a notification to x.a? 
2) Or, are you saying that when you modify an element of x.a, perhaps changing a property on x.a[0], that x is getting a notification? 
3) Or something else?

**Comment by dmiorandi** [comment]
1) is the one
2) I'm not sure about this probably if item in array change ref x is notified else not

Anyway I suppose this behaviors is by design, is this right?
Actually I've changed my code to ignore it. The intent of this issue is to understand if it's by design
and if there is a better way to do what I'm doing.
