### ISSUE TITLE
Huge object delivery performance

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#8]
I've got a huge json observed (on an angular app) and on every change a 10MB object is delivered
, so that my application became unusable.

I'm wondering if should be possible doing the following things to delivery an essential object:
1. **oldobject**:  make configurable if delivery oldobject property or not (enable/disable on creation of observer)
2. **object**:  do like 1 but of course this is needed, so that observer could memorize a string path given on input in the observer and deliver that, so that user could extract from his context the inner path object just when needed.

In my case I've already got path on user callback side, so probably is not necessary to save it inside observer. I'm thinking about it...

Probably I'll try to implement it. Do you think if i find a working solution you could integrate these features?
What do you think about it? Have you got a better idea to avoid delivery of huge data

**Comment by anywhichway** [comment]
When you say "oldobject", I assume you mean the value stored in "oldValue" which might be a primitive or might be an object. If so, then I suppose we could add another constructor flag to suppress collection of oldValue. However, oldValue should just be a reference to an already existing object, not a copy, unless you are serializing and de-serializing stuff, so I am unsure how proxy-observe ends up adding a 10MB object.

**Comment by dmiorandi** [comment]
I'm investigating to better understand it. If it was a reference should be ok. I've made a patched library with no value and old value passed on delivery to make a performance comparision.

**Comment by dmiorandi** [comment]
Ok you are right. It was a pitfall. My performance issue is not related to observer, but to callback code.
Please forgive me for wrong issue.

**Comment by anywhichway** [comment]
no problem! glad you found the issue in your code and also glad you let me know.
