### ISSUE TITLE
cpu loaded by deliver

### ISSUE THREAD

**Issue by dmiorandi** [anywhichway/proxy-observe#9]
``` javascript
setTimeout(deliver,0);
```

This code produce a cpu load of 30% on my I5 cpu, without any changes on observed object.
This is due to time between two runs of deliver.
- if I set time to 1 cpu load goes down to 10%
- if I set time to 10 cpu load goes down to 6%
- if I set time to 100 cpu load goes down to less than 1%

I think an acceptable value should be **100 ms.** If a change callback are delayed of 100ms I think there is no issue at all, IMHO. Is it patchable?

A middle/long term consideration:
This is a trick, but the question is why you need an async delivery? Probably this is by design, but on
the flipside of the coin doing it in a sync way should not load cpu at all avoiding a polling cycle to deliver changes.
What do you think about it?

**Comment by anywhichway** [comment]
Researching this over the next few days...

**Comment by anywhichway** [comment]
We have modified the default delivery timeout to 10ms and posted as v0.0.16. We felt that 100ms would be too long for some uses. We have left the delivery as asynchronous for two reasons:

1) That is the way the original observer spec worked
2) If there are a lot of observed objects with cascading impacts a non-async delivery could bind up the application.

We are considering adding a property to the Object.observe function, Object.observe.deliveryTimeout = 10. If we do this, you could set any value you want, including -1 for synchronous delivery. Please let us know what you think about this approach.

**Comment by dmiorandi** [comment]
Great!
About your proposal of expose a parameter, it sounds good, so that if anyone needs a different
behavior it could just configure it. Also with -1 it would be synchronous. Simply perfect to me.

**Comment by anywhichway** [comment]
OK, we will push this next week.

**Comment by dmiorandi** [comment]
Any chances to have Object.observe.deliveryTimeout configurable parameters implemented?

**Comment by anywhichway** [comment]
We only modified so that it is set at 10 instead of 0. Argument list was getting kind of long and we did not have the time to switch to a config object and test. Will add an option this week and push a new version.

**Comment by anywhichway** [comment]
turns out this was in development, should have a push tomorrow

**Comment by dmiorandi** [comment]
ok tks @anywhichway

**Comment by anywhichway** [comment]
Ehanced to take a 6th argument, `delay`, to set delivery timeout on changes in milliseconds. Also reduced CPU load by making the delivery function "smart". Delivery no longer creates timeout calls if there is nothing to deliver. The next change to an object will restart the delivery function with the previous delay setting.

**Comment by dmiorandi** [comment]
It sounds good, I'm going to try it on Monday tks @anywhichway
